name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        env:
          GHCR_TOKEN: ${{ secrets.LEAFLINK_AUTOMATION_PAT }}

      - name: build and push latest docker image to GCR
        run: |
          docker build -t ghcr.io/LeafLink/aws-ecr-action:latest .
          docker tag ghcr.io/LeafLink/aws-ecr-action ghcr.io/LeafLink/aws-ecr-action:$GITHUB_SHA
          docker push ghcr.io/LeafLink/aws-ecr-action:latest
          docker push ghcr.io/LeafLink/aws-ecr-action:$GITHUB_SHA
